[plugins]
# Simple: plugin name = GitHub URL (uses default branch)
# tmux-ssh-split = "https://github.com/pschmitt/tmux-ssh-split"

# With specific version:
# 'laktak/extrakto'
dracula-theme = "https://github.com/dracula/tmux"
tmux-resurrect = "https://github.com/tmux-plugins/tmux-resurrect"
tmux-continuum = "https://github.com/tmux-plugins/tmux-continuum"
tmux-nerd-name = "https://github.com/joshmedeski/tmux-nerd-font-window-name"
tmux-fingers = { url = "https://github.com/Morantron/tmux-fingers", branch = "master" }
# tmux-sensible = { url = "https://github.com/tmux-plugins/tmux-sensible", tag = "v2.0.3" }
