"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 3]
show_hidden = true
show_symlink = true
sort_reverse = false
sort_sensitive = true
sort_dir_first = true
linemode = "size"
sort_by = "alphabetical"

[preview]
tab_size = 2
max_width = 2000
max_height = 2000
