"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 3]
show_hidden = true
show_symlink = true
sort_reverse = false
sort_sensitive = true
sort_dir_first = true
linemode = "size"
sort_by = "alphabetical"

[preview]
tab_size = 2
max_width = 2000
max_height = 2000

[plugin]
prepend_previewers = [
    { name = "*.md", run = "glow" },
    { mime = "text/csv", run = "miller" },
    # Archive previewer
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
]

[opener]
extract = [
    { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
