
# [env]
# TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "JetBrains Maple Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Maple Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Maple Mono"
style = "Italic"

[font.normal]
family = "JetBrains Maple Mono"
style = "Regular"

[hints]
alphabet = "jklfdsaiohgurewpq"

[[hints.enabled]]
command = "open"
hyperlinks = true
mouse.enabled = true
post_processing = true
binding = { key = "U", mods = "Command|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
    { chars = "\u001Bf", key = "F", mods = "Command" },

    { chars = "\u001Bb", key = "B", mods = "Command" },

    { chars = "\u001Bd", key = "D", mods = "Command" },

    { chars = "\u0007g", key = "G", mods = "Command" },

    { chars = "\u0007f", key = "Y", mods = "Command" },

    { chars = "\u0007c", key = "C", mods = "Command" },

    { chars = "\u0007e", key = "E", mods = "Command" },

    { chars = "\u0007n", key = "N", mods = "Command" },

    { chars = "\u0007u", key = "U", mods = "Command" },

    { chars = "\u0007t", key = "T", mods = "Command" },

    { chars = "\u0007r", key = "R", mods = "Command" },

    { chars = "\u0007o", key = "O", mods = "Command" },

    { chars = "\u0007z", key = "Z", mods = "Command" },

    { chars = "\u0007M", key = "M", mods = "Command" },

    { chars = "\u0007P", key = "P", mods = "Command" },

    { chars = "\u0007|", key = "I", mods = "Command" },

    { chars = "\u0007-", key = "S", mods = "Command" },

    { chars = "\u0007x", key = "X", mods = "Command" },

    { chars = "\u0007&", key = "W", mods = "Command" },

    { chars = "\u0007,", key = "Comma", mods = "Command" },

    { chars = "\u0007}", key = "Period", mods = "Command" },

    { chars = "\u0007c?", key = "Slash", mods = "Command" },

    { chars = "\u0007k", key = "K", mods = "Command" },

    { chars = "\u0007j", key = "J", mods = "Command" },

    { chars = "\u0007l", key = "L", mods = "Command" },

    # { chars = "\u0007h", key = "H", mods = "Command" },
    # { chars = "\u0007h", key = "R", mods = "Command" },

    { chars = "\u0007k", key = "Up", mods = "Command" },

    { chars = "\u0007j", key = "Down", mods = "Command" },

    { chars = "\u0007h", key = "Left", mods = "Command" },

    { chars = "\u0007l", key = "Right", mods = "Command" },

    { chars = "\u0007F", key = "F", mods = "Command|Shift" },

    { chars = "\u0007K", key = "K", mods = "Command|Shift" },

    { chars = "\u0007J", key = "J", mods = "Command|Shift" },

    { chars = "\u0007H", key = "H", mods = "Command|Shift" },

    { chars = "\u0007L", key = "L", mods = "Command|Shift" },

    { chars = "\u0007K", key = "Up", mods = "Command|Shift" },

    { chars = "\u0007J", key = "Down", mods = "Command|Shift" },

    { chars = "\u0007H", key = "Left", mods = "Command|Shift" },

    { chars = "\u0007L", key = "Right", mods = "Command|Shift" },

    { chars = "\u00071", key = "Key1", mods = "Command" },

    { chars = "\u00072", key = "Key2", mods = "Command" },

    { chars = "\u00073", key = "Key3", mods = "Command" },

    { chars = "\u00074", key = "Key4", mods = "Command" },

    { chars = "\u00075", key = "Key5", mods = "Command" },

    { chars = "\u00076", key = "Key6", mods = "Command" },

    { chars = "\u00077", key = "Key7", mods = "Command" },

    { chars = "\u00078", key = "Key8", mods = "Command" },

    { chars = "\u0007e", key = "Key9", mods = "Command" },

    { action = "ReceiveChar", key = "Back" },

    { action = "ResetFontSize", key = "Key0", mods = "Command" },

    { action = "IncreaseFontSize", key = "Plus", mods = "Command" },

    { action = "DecreaseFontSize", key = "Minus", mods = "Command" },

    { action = "SearchBackward", key = "S", mode = "~Search", mods = "Shift|Command" },

    { action = "ScrollToBottom", key = "B", mode = "Vi|~Search", mods = "Shift|Command" },

    { action = "ToggleViMode", key = "Space", mode = "~Vi|~Search", mods = "Shift|Command" },

    { key = "N", mods = "Command|Shift", command = { program = "/usr/local/bin/alacritty", args = [
        "msg",
        "create-window",
        "-e",
        "/opt/homebrew/bin/fish",
    ] } },

]

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Middle", action = "PasteSelection" },
    { mouse = "Left", mods = "Control", action = "ExpandSelection" },
]

[cursor]
style.shape = "Beam"
vi_mode_style.shape = "Block"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:/\"' ()[]{}<>=-.\t"

[window]
opacity = 0.95
dynamic_padding = true
padding = { x = 3, y = 0 }
option_as_alt = "Both"
decorations = "buttonless"
startup_mode = "Maximized"

[scrolling]
multiplier = 6

[general]
live_config_reload = true
import = ["./themes/catppuccin-macchiato.toml"]

[terminal]

[terminal.shell]
args = ["--login", "-c", "tmux new-session -A -D -s  🚀"]
program = "/opt/homebrew/bin/zsh"
